use serde::Serialize;
use specta::Type;

#[derive(Debug, Serialize, Clone, Type)]
pub struct DockerEngineInfo {
    pub containers: String,
    pub containers_running: String,
    pub containers_paused: String,
    pub containers_stopped: String,
    pub images: String,
    pub containers_running_percent: f64,
    pub containers_paused_percent: f64,
    pub containers_stopped_percent: f64,
    pub server_version: String,
    pub api_version: String,
    pub name: String,
    pub ncpu: String,
    pub mem_total: String,
    pub os: String,
    pub os_version: String,
    pub kernel_version: String,
    pub architecture: String,
    pub storage_driver: String,
    pub warnings: String,
    pub warning_details: Vec<String>,
    pub docker_root_dir: String,
    pub logging_driver: String,
    pub cgroup_driver: String,
    pub cgroup_version: String,
    pub os_type: String,
    pub system_time: String,
    pub default_runtime: String,
    pub runtimes: Vec<String>,
    pub security_options: Vec<String>,
    pub live_restore_enabled: bool,
    pub experimental_build: bool,
    pub debug: bool,
    pub ipv4_forwarding: bool,
    pub http_proxy: String,
    pub https_proxy: String,
    pub no_proxy: String,
    pub memory_limit: bool,
    pub swap_limit: bool,
    pub cpu_cfs_period: bool,
    pub cpu_cfs_quota: bool,
    pub cpu_shares: bool,
    pub cpu_set: bool,
    pub pids_limit: bool,
    pub oom_kill_disable: bool,
    pub labels: Vec<String>,
    pub storage_driver_status: Vec<String>,
    pub volume_plugins: Vec<String>,
    pub network_plugins: Vec<String>,
    pub authorization_plugins: Vec<String>,
    pub log_plugins: Vec<String>,
    pub firewall_driver: String,
    pub firewall_info: Vec<String>,
}
