// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getServers: () => __TAURI_INVOKE<ServerConfig[]>("get_servers"),
	addServer: (server: ServerConfig) => __TAURI_INVOKE<ServerConfig[]>("add_server", { server }),
	updateServer: (server: ServerConfig) => __TAURI_INVOKE<ServerConfig[]>("update_server", { server }),
	deleteServer: (id: string) => __TAURI_INVOKE<ServerConfig[]>("delete_server", { id }),
	testConnection: (serverId: string) => __TAURI_INVOKE<string>("test_connection", { serverId }),
	testConnectionDirect: (server: ServerConfig) => __TAURI_INVOKE<string>("test_connection_direct", { server }),
	listContainers: (serverId: string) => __TAURI_INVOKE<Container[]>("list_containers", { serverId }),
	startContainer: (serverId: string, containerId: string) => __TAURI_INVOKE<null>("start_container", { serverId, containerId }),
	stopContainer: (serverId: string, containerId: string) => __TAURI_INVOKE<null>("stop_container", { serverId, containerId }),
	restartContainer: (serverId: string, containerId: string) => __TAURI_INVOKE<null>("restart_container", { serverId, containerId }),
	removeContainer: (serverId: string, containerId: string, force: boolean) => __TAURI_INVOKE<null>("remove_container", { serverId, containerId, force }),
	inspectContainer: (serverId: string, containerId: string) => __TAURI_INVOKE<string>("inspect_container", { serverId, containerId }),
	getContainerLogs: (serverId: string, containerId: string, tail: number, timestamps: boolean) => __TAURI_INVOKE<string>("get_container_logs", { serverId, containerId, tail, timestamps }),
	runContainer: (serverId: string, params: RunContainer) => __TAURI_INVOKE<string>("run_container", { serverId, params }),
	listImages: (serverId: string) => __TAURI_INVOKE<Image[]>("list_images", { serverId }),
	inspectImage: (serverId: string, imageId: string) => __TAURI_INVOKE<string>("inspect_image", { serverId, imageId }),
	getImageHistory: (serverId: string, imageId: string) => __TAURI_INVOKE<ImageLayer[]>("get_image_history", { serverId, imageId }),
	removeImage: (serverId: string, imageId: string, force: boolean) => __TAURI_INVOKE<null>("remove_image", { serverId, imageId, force }),
	startImagePull: (serverId: string, image: string) => __TAURI_INVOKE<string>("start_image_pull", { serverId, image }),
	cancelStream: (streamId: string) => __TAURI_INVOKE<void>("cancel_stream", { streamId }),
	listNetworks: (serverId: string) => __TAURI_INVOKE<Network[]>("list_networks", { serverId }),
	createNetwork: (serverId: string, params: NetworkCreate) => __TAURI_INVOKE<null>("create_network", { serverId, params }),
	inspectNetwork: (serverId: string, networkId: string) => __TAURI_INVOKE<string>("inspect_network", { serverId, networkId }),
	removeNetwork: (serverId: string, networkId: string) => __TAURI_INVOKE<null>("remove_network", { serverId, networkId }),
	listVolumes: (serverId: string) => __TAURI_INVOKE<Volume[]>("list_volumes", { serverId }),
	createVolume: (serverId: string, name: string, driver: string | null, driverOpts: { [key in string]: string } | null) => __TAURI_INVOKE<null>("create_volume", { serverId, name, driver, driverOpts }),
	inspectVolume: (serverId: string, name: string) => __TAURI_INVOKE<string>("inspect_volume", { serverId, name }),
	removeVolume: (serverId: string, name: string) => __TAURI_INVOKE<null>("remove_volume", { serverId, name }),
	checkDockerAccess: (serverId: string) => __TAURI_INVOKE<null>("check_docker_access", { serverId }),
	getDockerInfo: (serverId: string) => __TAURI_INVOKE<DockerEngineInfo>("get_docker_info", { serverId }),
	getContainerStats: (serverId: string, containerId: string) => __TAURI_INVOKE<ContainerStats>("get_container_stats", { serverId, containerId }),
	getDockerDaemonSettings: (serverId: string) => __TAURI_INVOKE<DaemonSettings>("get_docker_daemon_settings", { serverId }),
	updateDockerDaemonSettings: (serverId: string, params: DaemonUpdate) => __TAURI_INVOKE<null>("update_docker_daemon_settings", { serverId, params }),
	restartDockerDaemon: (serverId: string, sudoPassword: string | null) => __TAURI_INVOKE<null>("restart_docker_daemon", { serverId, sudoPassword }),
	startLogStream: (serverId: string, containerId: string, tail: number, timestamps: boolean) => __TAURI_INVOKE<string>("start_log_stream", { serverId, containerId, tail, timestamps }),
	stopLogStream: (streamId: string) => __TAURI_INVOKE<void>("stop_log_stream", { streamId }),
	startEventStream: (serverId: string) => __TAURI_INVOKE<string>("start_event_stream", { serverId }),
	stopEventStream: (serverId: string) => __TAURI_INVOKE<void>("stop_event_stream", { serverId }),
	listLocalAddresses: () => __TAURI_INVOKE<LocalAddress[]>("list_local_addresses"),
	listPortForwards: (serverId: string) => __TAURI_INVOKE<PortForward[]>("list_port_forwards", { serverId }),
	listPortForwardsAll: () => __TAURI_INVOKE<PortForward[]>("list_port_forwards_all"),
	createPortForwardRule: (serverId: string, params: PortForwardCreate) => __TAURI_INVOKE<PortForward>("create_port_forward_rule", { serverId, params }),
	setPortForwardEnabled: (id: string, enabled: boolean) => __TAURI_INVOKE<null>("set_port_forward_enabled", { id, enabled }),
	deletePortForward: (id: string) => __TAURI_INVOKE<null>("delete_port_forward", { id }),
	startAllEnabled: (serverId: string) => __TAURI_INVOKE<null>("start_all_enabled", { serverId }),
	startAllEnabledGlobal: () => __TAURI_INVOKE<null>("start_all_enabled_global"),
	stopAllGlobal: () => __TAURI_INVOKE<null>("stop_all_global"),
	stopPortForward: (id: string) => __TAURI_INVOKE<null>("stop_port_forward", { id }),
	openTerminal: (serverId: string, cols: number, rows: number) => __TAURI_INVOKE<TerminalSession>("open_terminal", { serverId, cols, rows }),
	openContainerExecTerminal: (serverId: string, params: ContainerExecTerminalParams) => __TAURI_INVOKE<TerminalSession>("open_container_exec_terminal", { serverId, params }),
	closeTerminal: (sessionId: string) => __TAURI_INVOKE<null>("close_terminal", { sessionId }),
	syncAppstore: () => __TAURI_INVOKE<string>("sync_appstore"),
	listApps: () => __TAURI_INVOKE<AppListItem[]>("list_apps"),
	getAppDetail: (appKey: string) => __TAURI_INVOKE<AppDetail_Serialize>("get_app_detail", { appKey }),
	installApp: (serverId: string, req: InstallAppRequest) => __TAURI_INVOKE<InstalledApp>("install_app", { serverId, req }),
	uninstallApp: (installId: string) => __TAURI_INVOKE<null>("uninstall_app", { installId }),
	listInstalledApps: (serverId: string | null) => __TAURI_INVOKE<InstalledApp[]>("list_installed_apps", { serverId }),
	operateInstalledApp: (installId: string, operation: string) => __TAURI_INVOKE<string>("operate_installed_app", { installId, operation }),
	getInstalledAppStatus: (installId: string) => __TAURI_INVOKE<string>("get_installed_app_status", { installId }),
};

/** Events */
export const events = {
	dockerSshStreamChunk: makeEvent<DockerSshStreamChunk>("docker-ssh-stream-chunk"),
	dockerSshStreamDone: makeEvent<DockerSshStreamDone>("docker-ssh-stream-done"),
	dockerStreamError: makeEvent<DockerStreamError>("docker-stream-error"),
	dockerStreamPayload: makeEvent<DockerStreamPayload>("docker-stream-payload"),
	dockerStreamRefresh: makeEvent<DockerStreamRefresh>("docker-stream-refresh"),
	dockerStreamStatus: makeEvent<DockerStreamStatus>("docker-stream-status"),
};

/* Types */
// 传递给前端的应用详情
export type AppDetail = AppDetail_Serialize | AppDetail_Deserialize;

// 传递给前端的应用详情
export type AppDetail_Deserialize = {
	key: string,
	name: string,
	tags: string[],
	description: DescriptionI18n,
	short_desc_zh: string,
	short_desc_en: string,
	website: string,
	github: string,
	document: string,
	icon: string,
	installed: boolean,
	versions: AppVersionInfo_Deserialize[],
	readme_zh: string,
	readme_en: string,
};

// 传递给前端的应用详情
export type AppDetail_Serialize = {
	key: string,
	name: string,
	tags: string[],
	description: DescriptionI18n,
	short_desc_zh: string,
	short_desc_en: string,
	website: string,
	github: string,
	document: string,
	icon: string,
	installed: boolean,
	versions: AppVersionInfo_Serialize[],
	readme_zh: string,
	readme_en: string,
};

// 传递给前端的应用列表项（含已安装状态）
export type AppListItem = {
	key: string,
	name: string,
	type: string,
	tags: string[],
	description: string,
	short_desc_zh: string,
	short_desc_en: string,
	website: string,
	icon: string,
	installed: boolean,
	versions: string[],
};

export type AppVersionInfo = AppVersionInfo_Serialize | AppVersionInfo_Deserialize;

export type AppVersionInfo_Deserialize = {
	version: string,
	form_fields: FormField_Deserialize[],
	compose_preview: string,
};

export type AppVersionInfo_Serialize = {
	version: string,
	form_fields: FormField_Serialize[],
	compose_preview: string,
};

export type Container = {
	id: string,
	name: string,
	image: string,
	status: string,
	state: string,
	stack: string,
	ip: string,
	ports: string,
	created_ts: number,
	volumes: string[],
};

export type ContainerExecTerminalParams = {
	container_id: string,
	user: string | null,
	shell: string,
	cols: number,
	rows: number,
};

export type ContainerStats = {
	cpu_percent: number,
	mem_usage: number,
	mem_limit: number,
	mem_percent: number,
	net_rx: number,
	net_tx: number,
	blk_read: number,
	blk_write: number,
};

export type DaemonSettings = {
	mirror_urls: string[],
	log_rotation: boolean,
	log_max_size: string,
	log_max_file: string,
	live_restore: boolean,
	cgroup_driver: string,
	socket_path: string,
};

export type DaemonUpdate = {
	mirror_urls: string[],
	log_rotation: boolean,
	log_max_size: string,
	log_max_file: string,
	live_restore: boolean,
	cgroup_driver: string,
	socket_path: string,
	sudo_password: string | null,
};

export type DescriptionI18n = {
	en?: string,
	"es-es"?: string,
	ja?: string,
	ms?: string,
	"pt-br"?: string,
	ru?: string,
	ko?: string,
	"zh-Hant"?: string,
	zh?: string,
	tr?: string,
};

export type DockerEngineInfo = {
	containers: number,
	containers_running: number,
	containers_paused: number,
	containers_stopped: number,
	images: number,
	server_version: string,
	api_version: string,
	name: string,
	ncpu: number,
	mem_total: number,
	os: string,
	os_version: string,
	kernel_version: string,
	architecture: string,
	storage_driver: string,
	warnings: number,
};

export type DockerEvent = {
	event_type: string,
	action: string,
	actor_id: string,
	actor_name: string,
	actor_image: string,
	scope: string,
	time: number,
	time_nano: number,
	detail: string,
};

export type DockerSshStreamChunk = {
	stream_id: string,
	chunk: string,
};

export type DockerSshStreamDone = {
	stream_id: string,
	success: boolean,
};

export type DockerStreamError = {
	stream_id: string,
	message: string,
};

export type DockerStreamPayload = {
	stream_id: string,
	event: DockerEvent,
};

export type DockerStreamRefresh = {
	stream_id: string,
	resource: string,
};

export type DockerStreamStatus = {
	stream_id: string,
	status: EventStreamStatus,
};

export type EventStreamStatus = "connecting" | "connected" | "disconnected" | "stopped";

export type FormField = FormField_Serialize | FormField_Deserialize;

export type FormFieldLabel = {
	en?: string,
	"es-es"?: string,
	ja?: string,
	ms?: string,
	"pt-br"?: string,
	ru?: string,
	ko?: string,
	"zh-Hant"?: string,
	zh?: string,
	tr?: string,
};

export type FormFieldValue = {
	label: string,
	value: string,
};

export type FormField_Deserialize = {
	envKey: string,
	default?: string,
	label: FormFieldLabel,
	required?: boolean,
	type?: string,
	values?: FormFieldValue[],
	random?: boolean,
	rule?: string,
};

export type FormField_Serialize = {
	envKey: string,
	default: string,
	label: FormFieldLabel,
	required: boolean,
	type: string,
	values: FormFieldValue[],
	random: boolean,
	rule: string,
};

export type Image = {
	id: string,
	repository: string,
	tag: string,
	size: string,
	created_ts: number,
	used_by_count: number,
};

export type ImageLayer = {
	id: string,
	created_ts: number,
	size: number,
	command: string,
	comment: string,
};

// 安装应用的请求参数
export type InstallAppRequest = {
	server_id: string,
	app_key: string,
	version: string,
	// 用户填写的环境变量值，key=envKey, value=用户输入
	env_values: { [key in string]: string },
};

// 已安装的应用信息
export type InstalledApp = {
	install_id: string,
	app_key: string,
	app_name: string,
	version: string,
	server_id: string,
	install_path: string,
	status: string,
	created_at: string,
};

export type LocalAddress = {
	ip: string,
	name: string,
};

export type Network = {
	id: string,
	name: string,
	driver: string,
	scope: string,
	created_at: string,
	subnets: string[],
	gateways: string[],
	labels: string[],
	internal: boolean,
	attachable: boolean,
};

export type NetworkCreate = {
	name: string,
	driver: string | null,
	subnet: string | null,
	gateway: string | null,
	internal: boolean,
	attachable: boolean,
};

export type PortForward = {
	id: string,
	server_id: string,
	container_id: string,
	container_name: string | null,
	enabled: boolean,
	protocol: string,
	container_port: number,
	remote_host: string,
	remote_port: number,
	local_port: number,
	bind_address: string,
	running: boolean,
	tx_bytes: number,
	rx_bytes: number,
	last_error: string | null,
};

export type PortForwardCreate = {
	container_id: string,
	container_name: string | null,
	remote_host: string,
	remote_port: number,
	container_port: number,
	protocol: string,
	local_port: number,
	bind_address: string | null,
	enabled: boolean,
};

export type RunContainer = {
	image: string,
	name: string | null,
	env?: string[],
	ports?: RunContainerPortSpec[],
	volumes?: RunContainerVolumeSpec[],
	restart_policy: string,
	restart_max_retry?: number | null,
	publish_all_ports?: boolean,
	network?: string,
	ipv4_address?: string,
	ipv6_address?: string,
	command?: string[],
	entrypoint?: string[],
	labels?: string[],
	auto_remove?: boolean,
	privileged?: boolean,
	tty?: boolean,
	open_stdin?: boolean,
	cpu_shares?: number,
	cpu_quota_cores?: number,
	memory_mb?: number,
};

export type RunContainerPortSpec = {
	container_port: number,
	host_port: number | null,
	protocol?: string,
};

export type RunContainerVolumeSpec = {
	host_path: string,
	container_path: string,
	read_only?: boolean,
};

export type ServerConfig = {
	id: string,
	name: string,
	host: string,
	port: number,
	username: string,
	auth_type: string,
	password: string | null,
	key_path: string | null,
};

export type TerminalSession = {
	session_id: string,
	ws_port: number,
};

export type Volume = {
	name: string,
	driver: string,
	mountpoint: string,
	scope: string,
	created_at: string,
	stack: string,
	used_by: string,
};

/* Tauri Specta runtime */
function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

