// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getServers: () => __TAURI_INVOKE<ServerConfig[]>("get_servers"),
	addServer: (server: ServerConfig) => __TAURI_INVOKE<ServerConfig[]>("add_server", { server }),
	updateServer: (server: ServerConfig) => __TAURI_INVOKE<ServerConfig[]>("update_server", { server }),
	deleteServer: (id: string) => __TAURI_INVOKE<ServerConfig[]>("delete_server", { id }),
	getPendingHostKey: () => __TAURI_INVOKE<{
	host: string,
	port: number,
	fingerprint: string,
	known_fingerprint: string | null,
} | null>("get_pending_host_key"),
	trustHostKey: (host: string, port: number, fingerprint: string) => __TAURI_INVOKE<null>("trust_host_key", { host, port, fingerprint }),
	listKnownHosts: () => __TAURI_INVOKE<KnownHostEntry[]>("list_known_hosts"),
	forgetHostKey: (host: string, port: number) => __TAURI_INVOKE<boolean>("forget_host_key", { host, port }),
	clearKnownHosts: () => __TAURI_INVOKE<number>("clear_known_hosts"),
	probeHostKey: (host: string, port: number) => __TAURI_INVOKE<string>("probe_host_key", { host, port }),
	testServerConnection: (serverId: string) => __TAURI_INVOKE<null>("test_server_connection", { serverId }),
	testServerConnectionDirect: (server: ServerConfig) => __TAURI_INVOKE<null>("test_server_connection_direct", { server }),
	listContainers: (serverId: string) => __TAURI_INVOKE<Container[]>("list_containers", { serverId }),
	startContainer: (serverId: string, containerId: string) => __TAURI_INVOKE<null>("start_container", { serverId, containerId }),
	stopContainer: (serverId: string, containerId: string) => __TAURI_INVOKE<null>("stop_container", { serverId, containerId }),
	restartContainer: (serverId: string, containerId: string) => __TAURI_INVOKE<null>("restart_container", { serverId, containerId }),
	removeContainer: (serverId: string, containerId: string, force: boolean) => __TAURI_INVOKE<null>("remove_container", { serverId, containerId, force }),
	pruneStoppedContainers: (serverId: string) => __TAURI_INVOKE<CleanupResult>("prune_stopped_containers", { serverId }),
	inspectContainer: (serverId: string, containerId: string) => __TAURI_INVOKE<string>("inspect_container", { serverId, containerId }),
	getContainerLogs: (serverId: string, containerId: string, tail: number, timestamps: boolean) => __TAURI_INVOKE<string>("get_container_logs", { serverId, containerId, tail, timestamps }),
	runContainer: (serverId: string, params: RunContainer) => __TAURI_INVOKE<string>("run_container", { serverId, params }),
	listImages: (serverId: string) => __TAURI_INVOKE<Image[]>("list_images", { serverId }),
	inspectImage: (serverId: string, imageId: string) => __TAURI_INVOKE<string>("inspect_image", { serverId, imageId }),
	getImageHistory: (serverId: string, imageId: string) => __TAURI_INVOKE<ImageLayer[]>("get_image_history", { serverId, imageId }),
	removeImage: (serverId: string, imageId: string, force: boolean) => __TAURI_INVOKE<null>("remove_image", { serverId, imageId, force }),
	pruneDanglingImages: (serverId: string) => __TAURI_INVOKE<CleanupResult>("prune_dangling_images", { serverId }),
	pruneUnusedImages: (serverId: string) => __TAURI_INVOKE<CleanupResult>("prune_unused_images", { serverId }),
	pruneBuilderCache: (serverId: string) => __TAURI_INVOKE<CleanupResult>("prune_builder_cache", { serverId }),
	exportImage: (exportId: string, serverId: string, imageId: string, directory: string, fileName: string) => __TAURI_INVOKE<null>("export_image", { exportId, serverId, imageId, directory, fileName }),
	importImage: (importId: string, serverId: string, filePath: string) => __TAURI_INVOKE<null>("import_image", { importId, serverId, filePath }),
	startImagePull: (serverId: string, image: string) => __TAURI_INVOKE<string>("start_image_pull", { serverId, image }),
	cancelStream: (streamId: string) => __TAURI_INVOKE<null>("cancel_stream", { streamId }),
	listNetworks: (serverId: string) => __TAURI_INVOKE<Network[]>("list_networks", { serverId }),
	createNetwork: (serverId: string, params: NetworkCreate) => __TAURI_INVOKE<null>("create_network", { serverId, params }),
	inspectNetwork: (serverId: string, networkId: string) => __TAURI_INVOKE<string>("inspect_network", { serverId, networkId }),
	removeNetwork: (serverId: string, networkId: string) => __TAURI_INVOKE<null>("remove_network", { serverId, networkId }),
	pruneUnusedNetworks: (serverId: string) => __TAURI_INVOKE<CleanupResult>("prune_unused_networks", { serverId }),
	listVolumes: (serverId: string) => __TAURI_INVOKE<Volume[]>("list_volumes", { serverId }),
	createVolume: (serverId: string, name: string, driver: string | null, driverOpts: { [key in string]: string } | null) => __TAURI_INVOKE<null>("create_volume", { serverId, name, driver, driverOpts }),
	inspectVolume: (serverId: string, name: string) => __TAURI_INVOKE<string>("inspect_volume", { serverId, name }),
	removeVolume: (serverId: string, name: string) => __TAURI_INVOKE<null>("remove_volume", { serverId, name }),
	pruneUnusedVolumes: (serverId: string) => __TAURI_INVOKE<CleanupResult>("prune_unused_volumes", { serverId }),
	checkDockerAccess: (serverId: string) => __TAURI_INVOKE<DockerEngineInfo>("check_docker_access", { serverId }),
	listSystemFonts: () => __TAURI_INVOKE<string[]>("list_system_fonts"),
	getDockerInfo: (serverId: string) => __TAURI_INVOKE<DockerEngineInfo>("get_docker_info", { serverId }),
	getContainerStats: (serverId: string, containerId: string) => __TAURI_INVOKE<ContainerStats>("get_container_stats", { serverId, containerId }),
	getDockerDaemonSettings: (serverId: string) => __TAURI_INVOKE<DaemonSettings>("get_docker_daemon_settings", { serverId }),
	updateDockerDaemonSettings: (serverId: string, params: DaemonUpdate) => __TAURI_INVOKE<null>("update_docker_daemon_settings", { serverId, params }),
	restartDockerDaemon: (serverId: string, sudoPassword: string | null) => __TAURI_INVOKE<null>("restart_docker_daemon", { serverId, sudoPassword }),
	openDevtools: () => __TAURI_INVOKE<null>("open_devtools"),
	getLogLevel: () => __TAURI_INVOKE<string>("get_log_level"),
	updateLogLevel: (level: string) => __TAURI_INVOKE<string>("update_log_level", { level }),
	getDependencyLogLevel: () => __TAURI_INVOKE<string>("get_dependency_log_level"),
	updateDependencyLogLevel: (level: string) => __TAURI_INVOKE<string>("update_dependency_log_level", { level }),
	startLogStream: (serverId: string, containerId: string, tail: number, timestamps: boolean) => __TAURI_INVOKE<string>("start_log_stream", { serverId, containerId, tail, timestamps }),
	stopLogStream: (streamId: string) => __TAURI_INVOKE<null>("stop_log_stream", { streamId }),
	startEventStream: (serverId: string) => __TAURI_INVOKE<string>("start_event_stream", { serverId }),
	stopEventStream: (serverId: string) => __TAURI_INVOKE<null>("stop_event_stream", { serverId }),
	listLocalAddresses: () => __TAURI_INVOKE<LocalAddress[]>("list_local_addresses"),
	listPortForwards: (serverId: string) => __TAURI_INVOKE<PortForward[]>("list_port_forwards", { serverId }),
	listPortForwardsAll: () => __TAURI_INVOKE<PortForward[]>("list_port_forwards_all"),
	createPortForwardRule: (serverId: string, params: PortForwardCreate) => __TAURI_INVOKE<PortForward>("create_port_forward_rule", { serverId, params }),
	setPortForwardEnabled: (id: string, enabled: boolean) => __TAURI_INVOKE<null>("set_port_forward_enabled", { id, enabled }),
	setPortForwardsEnabled: (ids: string[], enabled: boolean) => __TAURI_INVOKE<null>("set_port_forwards_enabled", { ids, enabled }),
	deletePortForward: (id: string) => __TAURI_INVOKE<null>("delete_port_forward", { id }),
	startAllEnabled: (serverId: string) => __TAURI_INVOKE<null>("start_all_enabled", { serverId }),
	startAllEnabledGlobal: () => __TAURI_INVOKE<null>("start_all_enabled_global"),
	stopAllGlobal: () => __TAURI_INVOKE<null>("stop_all_global"),
	startPortForward: (id: string) => __TAURI_INVOKE<null>("start_port_forward", { id }),
	stopPortForward: (id: string) => __TAURI_INVOKE<null>("stop_port_forward", { id }),
	openTerminal: (serverId: string, cols: number, rows: number) => __TAURI_INVOKE<TerminalSession>("open_terminal", { serverId, cols, rows }),
	openContainerExecTerminal: (serverId: string, params: ContainerExecTerminalParams) => __TAURI_INVOKE<TerminalSession>("open_container_exec_terminal", { serverId, params }),
	closeTerminal: (sessionId: string) => __TAURI_INVOKE<null>("close_terminal", { sessionId }),
	saveTerminalExport: (path: string, content: string) => __TAURI_INVOKE<null>("save_terminal_export", { path, content }),
	syncAppstore: () => __TAURI_INVOKE<null>("sync_appstore"),
	listApps: (sourceId: string | null) => __TAURI_INVOKE<AppListItem[]>("list_apps", { sourceId }),
	getAppstoreSettings: () => __TAURI_INVOKE<AppstoreSettings>("get_appstore_settings"),
	updateAppstoreSettings: (settings: AppstoreSettings) => __TAURI_INVOKE<AppstoreSettings>("update_appstore_settings", { settings }),
	getAppstoreCacheInfo: () => __TAURI_INVOKE<AppstoreCacheInfo>("get_appstore_cache_info"),
	clearAppstoreCache: () => __TAURI_INVOKE<null>("clear_appstore_cache"),
	getAppDetail: (sourceId: string | null, appKey: string) => __TAURI_INVOKE<AppDetail_Serialize>("get_app_detail", { sourceId, appKey }),
	installApp: (serverId: string, req: InstallApp) => __TAURI_INVOKE<null>("install_app", { serverId, req }),
};

/** Events */
export const events = {
	appstoreSyncProgress: makeEvent<AppstoreSyncProgress>("appstore-sync-progress"),
	dockerStreamError: makeEvent<DockerStreamError>("docker-stream-error"),
	dockerStreamPayload: makeEvent<DockerStreamPayload>("docker-stream-payload"),
	dockerStreamRefresh: makeEvent<DockerStreamRefresh>("docker-stream-refresh"),
	dockerStreamStatus: makeEvent<DockerStreamStatus>("docker-stream-status"),
	hostKeyPromptRequired: makeEvent<HostKeyPromptRequired>("host-key-prompt-required"),
	imageExportProgress: makeEvent<ImageExportProgress>("image-export-progress"),
	imageImportProgress: makeEvent<ImageImportProgress>("image-import-progress"),
	imagePullDone: makeEvent<ImagePullDone>("image-pull-done"),
	imagePullProgress: makeEvent<ImagePullProgress>("image-pull-progress"),
	installStepEvent: makeEvent<InstallStepEvent>("install-step-event"),
	portForwardSnapshot: makeEvent<PortForwardSnapshot>("port-forward-snapshot"),
};

/* Types */
export type AppDetail = AppDetail_Serialize | AppDetail_Deserialize;

export type AppDetail_Deserialize = {
	key: string,
	name: string,
	tags: string[],
	tags_en: string[],
	description: DescriptionI18n,
	short_desc_zh: string,
	short_desc_en: string,
	website: string,
	github: string,
	document: string,
	icon: string,
	versions: AppVersionInfo_Deserialize[],
	readme_zh: string,
	readme_en: string,
};

export type AppDetail_Serialize = {
	key: string,
	name: string,
	tags: string[],
	tags_en: string[],
	description: DescriptionI18n,
	short_desc_zh: string,
	short_desc_en: string,
	website: string,
	github: string,
	document: string,
	icon: string,
	versions: AppVersionInfo_Serialize[],
	readme_zh: string,
	readme_en: string,
};

/**
 *  面向前端的错误。不带任何用户可见文案：`code` 决定显示什么，
 *  文案与建议统一放在前端词条 `errors.<code>.{message,action}` 里。
 * 
 *  `params` 供词条插值，`detail` 是底层库抛出的原始错误串（不翻译，原样展示）。
 */
export type AppError = {
	code: string,
	kind: AppErrorKind,
	params: { [key in string]: string },
	detail: string | null,
	retryable: boolean,
};

export type AppErrorKind = "validation" | "auth" | "permission" | "not_found" | "conflict" | "unavailable" | "timeout" | "internal";

export type AppListItem = {
	key: string,
	name: string,
	type: string,
	tags: string[],
	tags_en: string[],
	description: DescriptionI18n,
	short_desc_zh: string,
	short_desc_en: string,
	website: string,
	icon: string,
	versions: string[],
};

export type AppVersionInfo = AppVersionInfo_Serialize | AppVersionInfo_Deserialize;

export type AppVersionInfo_Deserialize = {
	version: string,
	form_fields: FormField_Deserialize[],
	compose_preview: string,
};

export type AppVersionInfo_Serialize = {
	version: string,
	form_fields: FormField_Serialize[],
	compose_preview: string,
};

export type AppstoreCacheInfo = {
	cache_dir: string,
	exists: boolean,
	size: string,
};

export type AppstoreSettings = {
	sources: AppstoreSource[],
	proxy_enabled: boolean,
	proxy_url: string,
};

export type AppstoreSource = {
	id: string,
	name: string,
	repo_url: string,
	enabled: boolean,
};

export type AppstoreSyncProgress = {
	phase: string,
	received_objects: number,
	total_objects: number,
	indexed_objects: number,
	percent: number | null,
};

export type CleanupResult = {
	deleted_count: number,
	reclaimed: string,
};

export type Container = {
	id: string,
	name: string,
	image: string,
	status: string,
	state: string,
	stack: string,
	ip: string,
	ports: string,
	created_at: string,
	created_ago: string,
	volumes: string[],
};

export type ContainerExecTerminalParams = {
	container_id: string,
	user: string | null,
	shell: string,
	cols: number,
	rows: number,
};

export type ContainerStats = {
	cpu_percent: number | null,
	mem_percent: number | null,
	mem_usage: string,
	mem_limit: string,
	mem: string,
	net_rx: string,
	net_tx: string,
	net: string,
	blk_read: string,
	blk_write: string,
	blk: string,
};

export type DaemonSettings = {
	mirror_urls: string[],
	log_rotation: boolean,
	log_max_size: string,
	log_max_file: string,
	live_restore: boolean,
	cgroup_driver: string,
	socket_path: string,
};

export type DaemonUpdate = {
	mirror_urls: string[],
	log_rotation: boolean,
	log_max_size: string,
	log_max_file: string,
	live_restore: boolean,
	cgroup_driver: string,
	socket_path: string,
	sudo_password: string | null,
};

export type DescriptionI18n = {
	en?: string,
	"es-es"?: string,
	ja?: string,
	ms?: string,
	"pt-br"?: string,
	ru?: string,
	ko?: string,
	"zh-Hant"?: string,
	zh?: string,
	tr?: string,
};

export type DockerEngineInfo = {
	containers: string,
	containers_running: string,
	containers_paused: string,
	containers_stopped: string,
	images: string,
	containers_running_percent: number | null,
	containers_paused_percent: number | null,
	containers_stopped_percent: number | null,
	server_version: string,
	api_version: string,
	name: string,
	ncpu: string,
	mem_total: string,
	os: string,
	os_version: string,
	kernel_version: string,
	architecture: string,
	storage_driver: string,
	warnings: string,
	warning_details: string[],
	docker_root_dir: string,
	logging_driver: string,
	cgroup_driver: string,
	cgroup_version: string,
	os_type: string,
	system_time: string,
	default_runtime: string,
	runtimes: string[],
	security_options: string[],
	live_restore_enabled: boolean,
	experimental_build: boolean,
	debug: boolean,
	ipv4_forwarding: boolean,
	http_proxy: string,
	https_proxy: string,
	no_proxy: string,
	memory_limit: boolean,
	swap_limit: boolean,
	cpu_cfs_period: boolean,
	cpu_cfs_quota: boolean,
	cpu_shares: boolean,
	cpu_set: boolean,
	pids_limit: boolean,
	oom_kill_disable: boolean,
	labels: string[],
	storage_driver_status: string[],
	volume_plugins: string[],
	network_plugins: string[],
	authorization_plugins: string[],
	log_plugins: string[],
	firewall_driver: string,
	firewall_info: string[],
};

export type DockerEvent = {
	event_id: string,
	event_type: string,
	event_type_label: string,
	event_type_icon: string,
	action: string,
	action_tone: string,
	actor_id: string,
	actor_name: string,
	actor_image: string,
	scope: string,
	time: string,
	detail: string,
};

export type DockerStreamError = {
	stream_id: string,
	error: AppError,
};

export type DockerStreamPayload = {
	stream_id: string,
	event: DockerEvent,
};

export type DockerStreamRefresh = {
	stream_id: string,
	resource: string,
};

export type DockerStreamStatus = {
	stream_id: string,
	status: EventStreamStatus,
};

export type EventStreamStatus = "connecting" | "connected" | "disconnected" | "stopped";

export type FormField = FormField_Serialize | FormField_Deserialize;

export type FormFieldLabel = {
	en?: string,
	"es-es"?: string,
	ja?: string,
	ms?: string,
	"pt-br"?: string,
	ru?: string,
	ko?: string,
	"zh-Hant"?: string,
	zh?: string,
	tr?: string,
};

export type FormFieldValue = {
	label: string,
	value: string,
};

export type FormField_Deserialize = {
	envKey: string,
	default?: string,
	label: FormFieldLabel,
	required?: boolean,
	type?: string,
	values?: FormFieldValue[],
	random?: boolean,
	rule?: string,
};

export type FormField_Serialize = {
	envKey: string,
	default: string,
	label: FormFieldLabel,
	required: boolean,
	type: string,
	values: FormFieldValue[],
	random: boolean,
	rule: string,
};

export type HostKeyPrompt = {
	host: string,
	port: number,
	fingerprint: string,
	known_fingerprint: string | null,
};

/**  主机密钥校验失败时通知前端弹出确认框 */
export type HostKeyPromptRequired = {
	prompt: HostKeyPrompt,
};

export type Image = {
	id: string,
	repository: string,
	tag: string,
	size: string,
	created_at: string,
	created_ago: string,
	used_by_count: number,
};

export type ImageExportProgress = {
	export_id: string,
	image_id: string,
	transferred: string,
	total: string | null,
	percent: number | null,
};

export type ImageImportProgress = {
	import_id: string,
	file_name: string,
	transferred: string,
	total: string | null,
	percent: number | null,
};

export type ImageLayer = {
	id: string,
	created_at: string,
	size: string,
	command: string,
	comment: string,
};

export type ImagePullDone = {
	stream_id: string,
	success: boolean,
	error: AppError | null,
	final_status: string | null,
};

export type ImagePullLayerProgress = {
	id: string,
	status: string,
	current: string | null,
	total: string | null,
	percent: number | null,
};

export type ImagePullProgress = {
	stream_id: string,
	image: string,
	status: string,
	detail: string | null,
	layers: ImagePullLayerProgress[],
	completed_layers: number,
	total_layers: number,
};

export type InstallApp = {
	server_id: string,
	app_key: string,
	version: string,
	env_values: { [key in string]: string },
};

export type InstallStepEvent = {
	step: string,
	status: string,
	/**  词条 key（install.<name>），文案与插值由前端决定 */
	message_code: string,
	params: { [key in string]: string },
	output_chunk: string | null,
};

export type KnownHostEntry = {
	host: string,
	port: number,
	fingerprint: string,
};

export type LocalAddress = {
	ip: string,
	name: string,
};

export type Network = {
	id: string,
	name: string,
	driver: string,
	scope: string,
	created_at: string,
	created_ago: string,
	subnets: string[],
	gateways: string[],
	labels: string[],
	internal: boolean,
	attachable: boolean,
};

export type NetworkCreate = {
	name: string,
	driver: string | null,
	subnet: string | null,
	gateway: string | null,
	internal: boolean,
	attachable: boolean,
};

export type PortForward = {
	id: string,
	server_id: string,
	container_id: string,
	container_name: string | null,
	enabled: boolean,
	protocol: string,
	container_port: number,
	remote_host: string,
	remote_port: number,
	local_port: number,
	bind_address: string,
	running: boolean,
	tx_speed_bps: number | null,
	rx_speed_bps: number | null,
	last_error: PortForwardError | null,
};

export type PortForwardCreate = {
	container_id: string,
	container_name: string | null,
	remote_host: string,
	remote_port: number,
	container_port: number,
	protocol: string,
	local_port: number,
	bind_address: string | null,
	enabled: boolean,
};

export type PortForwardError = {
	error: AppError,
	at_ms: number,
};

export type PortForwardSnapshot = {
	forwards: PortForward[],
};

export type RunContainer = {
	image: string,
	name: string | null,
	env?: string[],
	ports?: RunContainerPortSpec[],
	volumes?: RunContainerVolumeSpec[],
	restart_policy: string,
	restart_max_retry?: number | null,
	publish_all_ports?: boolean,
	network?: string,
	ipv4_address?: string,
	ipv6_address?: string,
	command?: string[],
	entrypoint?: string[],
	labels?: string[],
	auto_remove?: boolean,
	privileged?: boolean,
	tty?: boolean,
	open_stdin?: boolean,
	cpu_shares?: number,
	cpu_quota_cores?: number | null,
	memory_mb?: number,
};

export type RunContainerPortSpec = {
	container_port: number,
	host_port: number | null,
	protocol?: string,
};

export type RunContainerVolumeSpec = {
	host_path: string,
	container_path: string,
	read_only?: boolean,
};

export type ServerConfig = {
	id: string,
	name: string,
	host: string,
	port: number,
	username: string,
	auth_type: string,
	password: string | null,
	key_path: string | null,
};

export type TerminalSession = {
	session_id: string,
	ws_port: number,
};

export type Volume = {
	name: string,
	driver: string,
	mountpoint: string,
	scope: string,
	created_at: string,
	created_ago: string,
	stack: string,
	used_by: string,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

